application: ggtodolist
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /client/do-me.manifest
  static_files: client/do-me.manifest
  mime_type: text/cache-manifest
  upload: client/do-me.manifest

- url: /client
  static_dir: client

- url: /.*
  script: app.app
