application: ggtodolist
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /client
  static_dir: client

- url: /.*
  script: app.app
